apiVersion: v1
kind: ServiceAccount
metadata:
  name: incident-agent
  namespace: ai-agent
  annotations:
    iam.gke.io/gcp-service-account: incident-agent@burner-chekrish1-6840.iam.gserviceaccount.com
automountServiceAccountToken: true
